### PR TITLE
Compute sorbent mass for prototype with small filters

### PR DESCRIPTION
**Pull request by thoralf-gutierrez**

### CODE REVIEW

**Comment by thoralf-gutierrez** [comment]
image

**Comment by thoralf-gutierrez** [comment]
I don't know if it's the best packing algorithm but it works well enough for our use case I think

**Comment by glimpens** [comment]
Works well and give a nice overview of the result.
I would advise to add 1 cm between each hole to avoid cracks.

Well done!

**Comment by glimpens** [comment]
Works well and give a nice overview of the result.
I would advise to add 1 cm between each hole to avoid cracks.

Well done!

**Pull request merged**
